# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Jekyll Metro'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
url:              'http://localhost:4000'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Abdel Raoof Olakara'
linkedin:       'https://ae.linkedin.com/in/olakara/'
twitter:        'https://twitter.com/olakara'
facebook:       'https://www.facebook.com/olakara'
gplus:          'https://plus.google.com/100425464897246255887/'

# Google Analytics
gahandler: 'UA-52149651-1'

#if footer-links-visible is 'true' the svg-icons will be shown top on the copy right. 
#else the svg icons will not exist
footersvg: 'false'

footer-links:
  dribbble: 
  email: zhufengdaaa@gmail.com
  facebook: 
  flickr: 
  github: ZhuFengdaaa
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  google: https://plus.google.com/u/0/116811442309236138007/about/p/pub
  twitter: None
  stackoverflow: #users/4388898/peter-zhu # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
